In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [14]:
A1 = array([[1.,0.,1.],[-3.,1.,-1.],[0.,-1.,-1.]])

invA1=linalg.inv(A1)

A2 = array([[1.,0.,0.],[-3,1.,1.],[0. ,0.,-2.0]])

x2 = array([0.0,0.0,1.0])

AinvA = matmul(invA1,A2)

x1 = -matmul(AinvA,x2)

print(A1)
print(A2)
print(x1)
print(x2)

[[ 1.  0.  1.]
 [-3.  1. -1.]
 [ 0. -1. -1.]]
[[ 1.  0.  0.]
 [-3.  1.  1.]
 [ 0.  0. -2.]]
[-1. -3.  1.]
[0. 0. 1.]
