In [6]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [7]:
A1 = array([[1.,1.,0.],[-3.,-1.,1],[0.,-1.,-2]])

invA1=linalg.inv(A1)

A2 = array([[1.,0.,0.],[-3.,1.,1.],[0.,-1.,0.]])

AinvA = matmul(invA1,A2)


x2_1 = array([1.,0.,0.])
x2_2 = array([0.,1.,0.])
x2_3 = array([0.,0.,1.])


x1_1 = -matmul(AinvA,x2_1)
x1_2 = -matmul(AinvA,x2_2)
x1_3 = -matmul(AinvA,x2_3)


print(x1_1)
print(x2_1)

print(x1_2)
print(x2_2)

print(x1_3)
print(x2_3)

[-1. -0. -0.]
[1. 0. 0.]
[ 0.33333333 -0.33333333 -0.33333333]
[0. 1. 0.]
[ 0.66666667 -0.66666667  0.33333333]
[0. 0. 1.]
